# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d057ffaca62aad6a925dbaecb285e0a58a3a19ec47c3ddfa4348217649a75cc1ef33d78b7b502248a062ef9ac46e7ce650fdbf4ea08726cd4893b21476d051b

test:
  secret_key_base: 04e349c01f6e3c0429223c34bfdaead18ab8075d387e375bd007c55ce1434e976e7c935061c2c8a39ded0fcad1f557bb78c6b40ba3b4c01adb78421f7e99d188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
